# Generated by Django 4.1.2 on 2022-11-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('zipcode', models.IntegerField(default=0)),
                ('skills', models.CharField(max_length=200)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('years', models.IntegerField(default=0)),
                ('education', models.CharField(blank=True, default='', max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
