# Generated by Django 4.1.3 on 2022-11-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstart', '0002_remove_recruiter_last_login_alter_recruiter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('postype', models.BooleanField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('expiration', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
