# Generated by Django 4.1.3 on 2022-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstart', '0004_jobposting_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='interested',
            field=models.IntegerField(default=0),
        ),
    ]
