# Generated by Django 4.1.3 on 2022-12-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstart', '0005_jobposting_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.IntegerField()),
                ('job', models.IntegerField()),
                ('interested', models.BooleanField()),
            ],
        ),
    ]
